spring:
  application:
    name: events-service

server:
  port: 8082

logging:
  level:
    org:
      apache:
        kafka: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health

bootstrap:
  servers: ${KAFKA_BROKERS:localhost:29092}

topic:
  movie:
    events: ${KAFKA_TOPIC_MOVIES:movie-events}
  user:
    events: ${KAFKA_TOPIC_USERS:user-events}
  payment:
    events: ${KAFKA_TOPIC_PAYMENTS:payment-events}
