apiVersion: v1
kind: ConfigMap
metadata:
  name: cinemaabyss-config
  namespace: cinemaabyss
data:
  # Database configuration
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "cinemaabyss"
  DB_USER: "postgres"

  # Kafka
  KAFKA_URL: "http://kafka:9092"

  # Service URLs
  MONOLITH_URL: "http://monolith:8080"
  MOVIES_SERVICE_URL: "http://movies-service:8081"
  EVENTS_SERVICE_URL: "http://events-service:8082"
  PROXY_SERVICE_URL: "gttp://proxy-service:8000"

  # Strangler Fig configuration
  GRADUAL_MIGRATION: "true"
  MOVIES_MIGRATION_PERCENT: "50"
