apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJlbVZ5WjI1ck9tZG9jRjkxZVdSUmRqSkZabGh4Umxkck0xUnBVa1pEVG5SblVrTTVlRkY0ZWxRelNtSkZNbGM9IiAKICAgIH0KICB9Cn0K
type: kubernetes.io/dockerconfigjson
