apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cinemaabyss-ingress
  namespace: cinemaabyss
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: "nginx"
  rules:
    - host: cinemaabyss.example.com
      http:
        paths:
         - path: /api/movies
           pathType: Prefix
           backend:
             service:
               name: proxy-service
               port:
                 number: 8000
         - path: /api/events
           pathType: Prefix
           backend:
             service:
               name: events-service
               port:
                 number: 8082
         - path: /api
           pathType: Prefix
           backend:
             service:
               name: monolith
               port:
                 number: 8080
