{{- if .Values.eventsService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: events-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.eventsService.replicas }}
  selector:
    matchLabels:
      app: events-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: events-service
    spec:
      containers:
      - name: events-service
        image: {{ .Values.eventsService.image.repository }}:{{ .Values.eventsService.image.tag }}
        imagePullPolicy: {{ .Values.eventsService.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.eventsService.service.targetPort }}
        env:
        - name: PORT
          value: "{{ .Values.eventsService.service.targetPort }}"
        - name: KAFKA_BROKERS
          value: "$(KAFKA_URL)"
        - name: KAFKA_TOPIC_MOVIES
          value: "movie-events"
        - name: KAFKA_TOPIC_USERS
          value: "user-events"
        - name: KAFKA_TOPIC_PAYMENTS
          value: "payment-events"
        envFrom:
        - configMapRef:
            name: cinemaabyss-config
        - secretRef:
            name: cinemaabyss-secrets
        resources:
          {{- toYaml .Values.eventsService.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: {{ .Values.eventsService.service.targetPort }}
          initialDelaySeconds: 60
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: {{ .Values.eventsService.service.targetPort }}
          initialDelaySeconds: 60
          periodSeconds: 30
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson

---
apiVersion: v1
kind: Service
metadata:
  name: events-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: events-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: events-service
  ports:
  - port: {{ .Values.eventsService.service.port }}
    targetPort: {{ .Values.eventsService.service.targetPort }}
  type: {{ .Values.eventsService.service.type }}
{{- end }}
